# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
 branches:
  include:
    - master
 paths:
   include:
     - NonBlockingAsync/NetCore/eBookStore

pool:
  vmImage: 'ubuntu-latest'

  

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build NonBlockingAsync/NetCore/eBookStore/eBookStore.csproj --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
