apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: ravitella/readinglist-springboot-mysql:latest
        ports:
         - containerPort: 7070
      - name: api
        image: ravitella/docker-springboot-recommendationservice:latest
        ports:
         - containerPort: 8080
---         
apiVersion: v1
kind: Service
metadata:
  labels:
    name: web
  name: web
spec:
  type: LoadBalancer
  ports:
    # The port that this service should serve on.
    - port: 80
      targetPort: 7070
  # Label keys and values that must match in order to receive traffic for this service.
  selector:
     app: web